name: Android CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run Coverage
      run: |
            chmod +x gradlew
            ./gradlew testDebugUnitTestCoverageVerification

    - name: Deploy coverage report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_dir: ${{ env.PR_NUMBER }}
    - name: Deploy coverage report v2
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch 
        git checkout -b gh-pages
        mkdir -p ${{ env.PR_NUMBER }}
        cp -R ${{github.workspace}}/app/build/reports/jacoco/testDebugUnitTestCoverage/html/* ${{ env.PR_NUMBER }}/
        git add --all
        git commit -m "Add coverage report ${PR_NUMBER}"
        git push origin gh-pages
